---

- name: Install psutil
  become: yes
  apt: 
    name: python-psutil

- include: facts.yml
- include: create-profile.yml


- name: Set keyboard shortcuts
  dconf: key="/org/gnome/terminal/legacy/keybindings/{{ item.name }}" value="'{{ item.value }}'"
  with_items:
  - { name: 'copy', value: '<Primary>c' }
  - { name: 'find', value: '<Primary>f' }
  - { name: 'new-tab', value: '<Primary>t' }
  - { name: 'new-window', value: '<Primary>n' }
  - { name: 'next-tab', value: '<Shift>Right' }
  - { name: 'paste', value: '<Primary>v' }
  - { name: 'prev-tab', value: '<Shift>Left' }
  - { name: 'reset-and-clear', value: '<Primary>k' }