---

- name: Check that kubefwd exists
  stat:
    path: /usr/local/bin/kubefwd
  register: stat_result
- name: Get latest release of kubefwd
  github_release:
    token: "{{ github_repos_public_mrdon }}"
    user: txn2
    repo: kubefwd
    action: latest_release
  when: stat_result.stat.exists == False
  register: kubefwd_release
- name: Download latest kubefwd release
  become: yes
  apt:
    deb: "https://github.com/txn2/kubefwd/releases/download/{{ kubefwd_release.tag}}/kubefwd_amd64.deb"
  when: stat_result.stat.exists == False

