---

- name: Check that kustomize exists
  stat:
    path: /usr/local/bin/kustomize
  register: stat_result
- name: Get latest release of kustomize
  github_release:
    token: "{{ github_repos_public_mrdon }}"
    user: kubernetes-sigs
    repo: kustomize
    action: latest_release
  when: stat_result.stat.exists == False
  register: kustomize_release
- name: Download latest kustomize release
  become: yes
  unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/{{ kustomize_release.tag}}/{{ kustomize_release.tag.replace('/','_') }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    mode: 755
  when: stat_result.stat.exists == False
