---
 
- name: Add yarn s official GPG key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
 
- name: Set up the stable repository
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    update_cache: yes
 
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
  
- name: Install yarn
  become: yes
  apt:
    name: yarn
    state: present
    update_cache: yes

  