---
- name: clone tb
  git:
    repo: https://bitbucket.org/mrdon/tb.git
    dest: "{{ src_dir }}/tb"

- name: Install tb deps
  pip:
    requirements: "{{ src_dir }}/tb/requirements-dev.txt"
    virtualenv: "{{ src_dir }}/tb/venv"
    virtualenv_command: /usr/bin/python3.8 -m venv

- name: Install tb
  pip:
    name: "{{ src_dir }}/tb"
    virtualenv: "{{ src_dir }}/tb/venv"
    virtualenv_command: /usr/bin/python3.8 -m venv
    editable: true

- name: Copy tb to local bin
  file:
    src: "{{ src_dir }}/tb/venv/bin/tb"
    dest: $HOME/.local/bin/tb
    state: link

