---

- name: Check that tic80 exists
  stat:
    path: /usr/local/bin/tic80
  register: stat_result
- name: Get latest release of tic80
  github_release:
    token: "{{ github_repos_public_mrdon }}"
    user: nesbox
    repo: TIC-80
    action: latest_release
  when: stat_result.stat.exists == False
  register: tic80_release
- name: Download latest tic80 release
  get_url:
    url: "https://github.com/nesbox/TIC-80/releases/download/{{ tic80_release.tag}}/tic80_{{ tic80_release.tag[1:] }}.tar.gz"
    dest: /tmp/tic80.tar.gz
  when: stat_result.stat.exists == False
- name: Install tic80
  become: yes
  unarchive:
    src: /tmp/tic80.tar.gz
    dest: /usr/local/bin
  when: stat_result.stat.exists == False

