---
 
# sudo apt-get install *
- name: Install docker packages
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes
 
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker s official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
 
# sudo apt-key fingerprint 0EBFCD88
- name: Verify that we have the key with the fingerprint
  become: yes
  apt_key:
    id: 0EBFCD88
    state: present
 
# sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: Set up the stable repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
 
# sudo apt-get update
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes
  
# sudo apt-get install docker-ce=18.03.*
- name: Install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Start docker on boot
  
# sudo groupadd docker
- name: Create "docker" group
  become: yes
  group:
    name: "docker"
    state: present
  
# sudo usermod -aG docker ubuntu
- name: Add current user to "docker" group
  become: yes
  user:
    name: "{{ user }}"
    group: "docker"
    append: yes
  
# sudo apt-get install docker-compose=1.8.*
- name: Install docker-compose
  become: yes
  apt:
    name: docker-compose
    state: present
    update_cache: yes
  