---

- name: Copy .vimrc
  file:
    src: "{{ playbook_dir }}/roles/dev/files/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
  with_items:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .bash_profile_git
    - .bash_profile_tmux
    - .bash_profile_bin

- name: Creates local bin directory
  file:
    path: $HOME/.local/bin
    state: directory

- name: Import python tasks
  include_tasks: python.yml

- name: Import docker tasks
  include_tasks: docker.yml

- name: Import nodejs tasks
  include_tasks: nodejs.yml

- name: Import apt tasks
  include_tasks: apt.yml

- name: Import flatpak tasks
  include_tasks: flatpak.yml

- name: Install snap applications
  become: yes
  snap:
    name:
      - whatsdesk
      - chromium
      - keepassxc
      - spotify
      - yq
- name: Install snap applications (classic)
  become: yes
  snap:
    classic: yes
    name:
      - sublime-text
      - slack
      - pycharm-community