---

- name: Copy .vimrc
  file:
    src: "{{ playbook_dir }}/roles/dev/files/.vimrc"
    dest: $HOME/.vimrc
    state: link
- name: Copy .bash_profile
  file:
    src: "{{ playbook_dir }}/roles/dev/files/.bash_profile"
    dest: $HOME/.bash_profile
    state: link

- name: Import python tasks
  include_tasks: python.yml

- name: Import docker tasks
  include_tasks: docker.yml

# - name: Install snap applications
#   snap:
#     name:
#       - whatsdesk
#       - chromium
#       - keepassxc
#       - spotify
# - name: Install snap applications (classic)
#   snap:
#     classic: yes
#     name:
#       - sublime-text
#       - slack
#       - pycharm-community