---
 
- name: Install prereq packages
  become: yes
  apt:
    name: ['software-properties-common']
    state: present
    update_cache: yes
 
# sudo apt-get update
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Install python 3.9
  become: yes
  apt:
     name: ['python3.9', 'python3.9-venv', 'python3.9-doc', 'python3.9-dev', 'python3-pip']
     state: present
     update_cache: yes
   
- name: Install python 3.8
  become: yes
  apt:
    name: ['python3.8', 'python3.8-venv', 'python3.8-doc', 'python3.8-dev']
    state: present
    update_cache: yes
  
