---
 
- name: Install prereq packages
  become: yes
  become_user: root
  apt:
    name: ['software-properties-common']
    state: present
    update_cache: yes
 
- name: Add deadsnakes repo
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
 
# sudo apt-get update
- name: Update apt packages
  become: yes
  become_user: root
  apt:
    update_cache: yes

- name: Install python 3.7
  become: yes
  become_user: root
  apt:
    name: ['python3.7', 'python3.7-venv', 'python3.7-doc', 'python3.7-dev', 'python3-pip']
    state: present
    update_cache: yes
  
- name: Install python 3.8
  become: yes
  become_user: root
  apt:
    name: ['python3.8', 'python3.8-venv', 'python3.8-doc', 'python3.8-dev']
    state: present
    update_cache: yes
  
